#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Mar 26 07:30:09 UTC 2022
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto fa5c301ab46040aeaed8d046dea713c6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot upcounter_testbench_behav xil_defaultlib.upcounter_testbench xil_defaultlib.glbl -log elaborate.log"
xelab -wto fa5c301ab46040aeaed8d046dea713c6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot upcounter_testbench_behav xil_defaultlib.upcounter_testbench xil_defaultlib.glbl -log elaborate.log

